@baseUrl=http://localhost:3003/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjZhODRhYjc0OTQ0NjE5OGRkMzQ1Y2ZlNSIsImlhdCI6MTc4OTQ5NzkwOH0.42egu5mNcPz8hlG5qRmjPObGr633DQjk-YwkvmApaTU

############ USERS ########

### Create User  ###
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "salasana"
}

### Get All Users ###
GET {{baseUrl}}/users

### Login ####
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "root",
  "password": "salasana"
}


############ BLOGS ########

### Get all blogs ###
GET {{baseUrl}}/blogs


### Create A Blog ###
POST {{baseUrl}}/blogs
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Learning Backend",
  "author": "McMnyages",
  "url": "https://example.com/fullstack",
  "likes": 30
}

### Delete A specific blog ###
DELETE {{baseUrl}}/blogs/6a7f2d8b0519bb42ac4566ee

### Edit A specific blog ###
PUT {{baseUrl}}/blogs/6a7f2bbea963968e694211ed
Content-Type: application/json

{
  "title": "Updated blog title",
  "author": "Updated Author",
  "url": "https://example.com/updated",
  "likes": 15
}


### 2. Add a comment to a specific blog
# Replace the ID in the URL below with one of the IDs you got from the GET request above
POST {{baseUrl}}/blogs/6aa9927643694f5dca15aba7/comments
Content-Type: application/json

{
  "comment": "This is an amazing blog post! 2"
}